### ISSUE TITLE
[BUG] Crash when creating new world

### ISSUE THREAD

**Issue by muhammedesadcomert** [AMPZNetwork/Dead-Light-Z#1]
**Describe the bug**
Game crashes when creating a new world.

**To Reproduce**
1. Go to "Singleplayer".
2. Click on "Create New World".
3. Create a new world.
4. See the crash.

**Expected behavior**
The world should create properly.

**Crash Log**
https://mclo.gs/sEAXFZf

**Basic Information (please complete the following information):**
 - OS: Windows 11 x64
 - Dead Light Z Version: 1.0
 - Platform: Prism Launcher
 - Extra mods added by you: OptiFine_1.18.2_HD_U_H7

**Comment by LabsZero** [comment]
Can you try and run the pack without Optifine

**Comment by muhammedesadcomert** [comment]
I will try it when I get a chance

**Comment by muhammedesadcomert** [comment]
@LabsZero I tested without Optifine and it works fine. Also, I tested with `OptiFine HD U H9 pre3` and the game does not crash. It seems like there is a problem with `OptiFine HD U H7`. The problem is probably fixed in the `OptiFine HD U H9` version.
You better add a note to the Optifine Recommendation section on the modpack page.

**Comment by LabsZero** [comment]
Good idea i will go ahead and mention it.

**Comment by LabsZero** [comment]
Added it. I shell closed this issue now.
